### ISSUE TITLE
The sky is the limit

### ISSUE THREAD

**Issue by DerKarlos** [DerKarlos/OSMeta#23]
* [x] Time after time tiles, visible in the frustum, should get loaded until "the sky"; the Skybox.
* [x] (While I really would prefer a sphere / a sky dome.)
* [x] This way, the distance to the sky is related to the GPU load. Slow user devices man need less distance.
* [ ] Seeing Buildings get visible "out of the sky" looks really odd!
  Fog would be better, but I only know fog at a linear line far away.
* [x] Of course the sky needs to be relative to the camera.
* [x] Some more distance behind the sky, in any direction, tiles may get removed to avoid memory overload.

**Comment by oli-obk** [comment]
We're using fog already, but it's very subtle. We need to tune it up when the sky is smaller

**Comment by oli-obk** [comment]
> May be dynamically according to the Sky size.

that's already happening. we can tune the parameters though. There are also other fog systems we can try out

**Comment by DerKarlos** [comment]
Some tests.  visibility: sky.scale.x * 
1.0 nice fading but dusty in the front
2.0 to less fading not dusty in the front
1.5. seems a not so good compromise
I am not sure if visibility is the "thickness".
Could the fog start may be 90% before the sky and go to 100% at the sky?

We need to take some time to experiment with the parameters.
We could add test parameter and led our user find the solution ;-)
