### ISSUE TITLE
Magic number 814.5

### ISSUE THREAD

**Issue by oli-obk** [DerKarlos/OSMeta#33]
I think that magic number is the length in meters of the tiles' sides. At least that is how we use it in the code. But how is it calculated from the zoom level?

**Comment by DerKarlos** [comment]
I did id a bit od:
In my *pos.rs was a function to calculate the position of a tile corner.
tile_size = (Tile+1).corner menus Tile.corner
But at last it is a constant by the size of the Earth and the number of decrees.
40'000km / 2^15  ?
40'000'000 / 32768 = 1220,7
  cos(48,5 Germany Passau) = 0,66262
1220,7 * 0,66262 =  808,86

https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames :
const EARTH_CIR_METERS = 40075016.686
metersEW = EARTH_CIR_METERS / Math.pow(2, zoom)   * Math.cos(lat)

810,379258925699463

And there is the Merkartor problem: To the poles, the width should get smaller, but NOT the height.
I have to discus this with Tobias.
And we may need to place the tiles not on a flat ground but a sphere.

**Comment by oli-obk** [comment]
![grafik](https://github.com/DerKarlos/OSMeta/assets/332036/ae196b9c-6e0f-4bcc-81d3-8a13bce90efb)

the tile surfaces are now in the right direction!

**Comment by oli-obk** [comment]
I added a function for computing tile sizes. Looks like Munich has approximately

```
1223m x 643m
```

but the glb tiles are squares and not rectangles that have half the height of their width.

Maybe my math is wrong? Can you check it? 

https://github.com/DerKarlos/OSMeta/blob/ceb6bc6137f197fdfd822599efe626fb70400439/src/geopos.rs#L69-L74

i got the width/height flipped, but otherwise it seems correct?

**Comment by oli-obk** [comment]
waaait... does osm simply say "equator length is 40k"? no matter the real value?

**Comment by DerKarlos** [comment]
No, the 40k was just my fuzzy memory. Osm uses
const EARTH_CIR_METERS = 40075016.686

**Comment by DerKarlos** [comment]
OSM uses Mercator projection (which always makes my brain dizzy). This is the correct solution, I hope:

To the poles, 
* tiles should get more slim but don't. They do show less W-E Meter, but they have same pixel count on 2D maps.
* Do let squares still be squares, the N-S direction gets stretched, the distant between the cyclic latitudes increases.
* But the OSM tiles do NOT get stretched, they get less N-S degrees! !! !!! <====
So all OSM tiles, also the GLB form Tobias have correct proportions, but are wrong to the real extensions.
We have to shrink the tiles near the poles, to get our spheric effect. (trigonometric)
The W-E distance is always the same in degree, but less in Meter.
The N-S distance gets less in degree and in Meter.

Really correct tiles should have different W-E dimensions on the N-S borders too. Not with Mercator!
This is only relevant near zoom 0. We only have 2D bitmaps there. Using UV values on the sphere should do it.
